# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54110fa359932d70f74aeb3b22abd46f8922739cbb57e70f91bd7464d2d019427c6021125b2aad769e66e63e35d0586dca8271122bb9b4e47b670a7000bfceb1

test:
  secret_key_base: 11f33f55d13742ee1f2b63958363a7b726e32254ac6704d3624e79f997caf956fe4b89f116a984c413f8ae161b03371ccca973f1c9ee2e6cdee369879d908083

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
